# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hubcave.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hubcave.proto',
  package='hubcave',
  serialized_pb=_b('\n\rhubcave.proto\x12\x07hubcave\"\xd8\x02\n\x03Map\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x12\n\nrepository\x18\x02 \x01(\t\x12-\n\x0b\x62lockmatrix\x18\x03 \x01(\x0b\x32\x18.hubcave.Map.BlockMatrix\x1a\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x1a\x8e\x01\n\x05\x42lock\x12\x30\n\x04type\x18\x01 \x02(\x0e\x32\x1c.hubcave.Map.Block.BlockType:\x04WALL\x12&\n\x05\x63oord\x18\x02 \x02(\x0b\x32\x17.hubcave.Map.Coordinate\"+\n\tBlockType\x12\n\n\x06GROUND\x10\x00\x12\x08\n\x04WALL\x10\x01\x12\x08\n\x04\x44OOR\x10\x02\x1aK\n\x0b\x42lockMatrix\x12\x0c\n\x04rows\x18\x01 \x02(\r\x12\x0c\n\x04\x63ols\x18\x02 \x02(\r\x12 \n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x12.hubcave.Map.Block')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MAP_BLOCK_BLOCKTYPE = _descriptor.EnumDescriptor(
  name='BlockType',
  full_name='hubcave.Map.Block.BlockType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GROUND', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WALL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOOR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=251,
  serialized_end=294,
)
_sym_db.RegisterEnumDescriptor(_MAP_BLOCK_BLOCKTYPE)


_MAP_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='hubcave.Map.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='hubcave.Map.Coordinate.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='hubcave.Map.Coordinate.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=149,
)

_MAP_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='hubcave.Map.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='hubcave.Map.Block.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coord', full_name='hubcave.Map.Block.coord', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MAP_BLOCK_BLOCKTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=294,
)

_MAP_BLOCKMATRIX = _descriptor.Descriptor(
  name='BlockMatrix',
  full_name='hubcave.Map.BlockMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='hubcave.Map.BlockMatrix.rows', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cols', full_name='hubcave.Map.BlockMatrix.cols', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='hubcave.Map.BlockMatrix.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=371,
)

_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='hubcave.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='hubcave.Map.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repository', full_name='hubcave.Map.repository', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blockmatrix', full_name='hubcave.Map.blockmatrix', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MAP_COORDINATE, _MAP_BLOCK, _MAP_BLOCKMATRIX, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=371,
)

_MAP_COORDINATE.containing_type = _MAP
_MAP_BLOCK.fields_by_name['type'].enum_type = _MAP_BLOCK_BLOCKTYPE
_MAP_BLOCK.fields_by_name['coord'].message_type = _MAP_COORDINATE
_MAP_BLOCK.containing_type = _MAP
_MAP_BLOCK_BLOCKTYPE.containing_type = _MAP_BLOCK
_MAP_BLOCKMATRIX.fields_by_name['data'].message_type = _MAP_BLOCK
_MAP_BLOCKMATRIX.containing_type = _MAP
_MAP.fields_by_name['blockmatrix'].message_type = _MAP_BLOCKMATRIX
DESCRIPTOR.message_types_by_name['Map'] = _MAP

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), dict(

  Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), dict(
    DESCRIPTOR = _MAP_COORDINATE,
    __module__ = 'hubcave_pb2'
    # @@protoc_insertion_point(class_scope:hubcave.Map.Coordinate)
    ))
  ,

  Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
    DESCRIPTOR = _MAP_BLOCK,
    __module__ = 'hubcave_pb2'
    # @@protoc_insertion_point(class_scope:hubcave.Map.Block)
    ))
  ,

  BlockMatrix = _reflection.GeneratedProtocolMessageType('BlockMatrix', (_message.Message,), dict(
    DESCRIPTOR = _MAP_BLOCKMATRIX,
    __module__ = 'hubcave_pb2'
    # @@protoc_insertion_point(class_scope:hubcave.Map.BlockMatrix)
    ))
  ,
  DESCRIPTOR = _MAP,
  __module__ = 'hubcave_pb2'
  # @@protoc_insertion_point(class_scope:hubcave.Map)
  ))
_sym_db.RegisterMessage(Map)
_sym_db.RegisterMessage(Map.Coordinate)
_sym_db.RegisterMessage(Map.Block)
_sym_db.RegisterMessage(Map.BlockMatrix)


# @@protoc_insertion_point(module_scope)
